# Generated by Django 5.1.7 on 2025-03-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refbook',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterField(
            model_name='element',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='refbooks.version', verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='refbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='refbooks.refbook', verbose_name='Справочник'),
        ),
        migrations.AlterField(
            model_name='version',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
    ]
